### ISSUE TITLE
comap files

### ISSUE THREAD

**Issue by amroibrahim** [JimMarshall35/acuta-soccer-mocap-viewer#1]
Hello, can you share how did you extract the *.comap files, looking at original source code for actua soccer a header file defining the indexes of the those files offsets seems to be missing. 

Thank you in advanced.

**Comment by JimMarshall35** [comment]
Hello Matey. These files were extracted from the Mac OS version of actual soccer, from the "Resource file". I can't recall which header file contained the offsets, a friend extracted them for me. The resource files are different on mac os, they can be browsed with a resource file browser and you can see what binaries are in them (to some extent) without needing a header to explain it. We do have access to pretty much the full mac OS source code to this game and can build it from source on a "Power PC" mac. Can I ask what you're interest in this game is? It could be we can collaborate together

**Comment by amroibrahim** [comment]
Hello, thanx for clarification, I will look into that. 
Yes sure I'm open for collaboration. My interested was to create a version of the game that would run on modern hardware, (Something similar to how Chocolate Doom is to Doom). Though initially I was thinking to go with a software renderer (since the code is open source), I'm okay with going the OpenGL route, It should make thing easier to implement. Do you have a project already started? If not we can come up with some goals and come up with with a plan.

**Comment by JimMarshall35** [comment]
what is your email mate? I will send you an email so we can copy my friend in (who's project this really is)

**Comment by JimMarshall35** [comment]
if you don't want your email made public you can email me mine is jimmarshall35@gmail.com

**Comment by amroibrahim** [comment]
I sent you an email, feel free to remove your email.
